### ISSUE TITLE
Quickstart guide lists same command for two different cases

### ISSUE THREAD

**Issue by benissimo** [pinot-contrib/pinot-docs#147]
https://docs.pinot.apache.org/basics/getting-started/quick-start#batch-json

```
docker run \
    -p 9000:9000 \
    apachepinot/pinot:0.9.3 QuickStart \
    -type batch_json_index
```

https://docs.pinot.apache.org/basics/getting-started/quick-start#batch-with-complex-data-types

```
docker run \
    -p 9000:9000 \
    apachepinot/pinot:0.9.3 QuickStart \
    -type batch_json_index
```

^ The two sections list the same quick start command. I assume this is a typo?

**Comment by xiangfu0** [comment]
Can you try latest pinot image `apachepinot/pinot:0.12.0` ?

**Comment by matthewhelmke** [comment]
Hi, I'm the new tech writer. I'm working to figure out what's going on here. The reporter is correct, the same command is listed in the quickstart doc for two separate examples.

We should probably check the launcher script commands, specifically the `-type` flags for these two examples.

I'm still ramping up, so it may take me a little time to figure this out. If anyone seeing this knows off the top of your head, please comment and I'll confirm and update. TIA

**Comment by matthewhelmke** [comment]
I got some help from one of our software engineers (thanks, Xiaobing!).

The code to launch the `Batch with complex data types` should use `batch_complex_type`, per this edited snippet:
```
class JsonIndexQuickStart ...

public List<String> types() {
  return Arrays.asList("OFFLINE_JSON_INDEX", "OFFLINE-JSON-INDEX", "BATCH_JSON_INDEX", "BATCH-JSON-INDEX"); // the cmd line finds the quick start by comparing with any of those names case insensatively 

class OfflineComplexTypeHandlingQuickStart ...
public List<String> types() {
    return Arrays.asList("OFFLINE_COMPLEX_TYPE", "OFFLINE-COMPLEX-TYPE", "BATCH_COMPLEX_TYPE", "BATCH-COMPLEX-TYPE");
```

The fix is in this commit: https://github.com/pinot-contrib/pinot-docs/commit/24fbc9327425622101d7276736007f435de72bf1

And with that, I'll close this issue.
