### ISSUE TITLE
Broken Links on basics/concepts/pinot-storage-model

### ISSUE THREAD

**Issue by khoramism** [pinot-contrib/pinot-docs#356]
Hey, Hope you guys are doing well, Here is a really minor issue, the link for, `See Ingestion` mentioned in this file is broken: https://github.com/pinot-contrib/pinot-docs/blob/latest/basics/concepts/pinot-storage-model.md#segment

here is the broken link:
- https://github.com/pinot-contrib/pinot-docs/blob/latest/developers/advanced/data-ingestion
- https://github.com/pinot-contrib/pinot-docs/blob/latest/basics/components/cluster/server/README.md

**Comment by Jackie-Jiang** [comment]
Thanks for reporting the issue! Do you want to help contribute a fix?

**Comment by khoramism** [comment]
sure :)

**Comment by khoramism** [comment]
I think we can close this, thanks :)
